# Generated by Django 4.2.1 on 2023-05-22 15:37

import app.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desc', models.CharField(max_length=255, verbose_name='desc')),
                ('number', models.IntegerField(max_length=16, validators=[app.validator.validate_even], verbose_name='number')),
            ],
        ),
    ]
